#!/usr/bin/env bash
# Reautentica Shopify CLI com scopes amplos — Empório Saibai
set -eu

STORE="${SHOPIFY_STORE:-byinbz-0k.myshopify.com}"

# Escopos bloqueados pelo app OAuth da CLI (400 missing_shopify_permission):
# read_checkout_settings, write_checkout_settings, read_shopify_payments, read_shopify_payments_accounts
SCOPES="read_analytics,read_content,write_content,read_themes,write_themes,read_products,write_products,read_inventory,write_inventory,read_files,write_files,read_online_store_navigation,write_online_store_navigation,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions,read_translations,write_translations,read_locales,write_locales,read_markets,write_markets,read_discounts,write_discounts,read_orders,write_orders,read_customers,write_customers,read_draft_orders,write_draft_orders,read_script_tags,write_script_tags,read_legal_policies,write_legal_policies,read_price_rules,write_price_rules,read_reports,write_reports,read_checkouts,write_checkouts,read_shipping,write_shipping,read_locations,read_product_listings,write_product_listings,read_resource_feedbacks,write_resource_feedbacks,read_purchase_options,write_purchase_options,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_gift_cards,write_gift_cards,read_payment_customizations,write_payment_customizations,read_delivery_customizations,write_delivery_customizations,read_validations,write_validations,read_store_credit_accounts,read_store_credit_account_transactions,write_store_credit_account_transactions,read_checkout_and_accounts_configurations,write_checkout_and_accounts_configurations"

echo "Store: $STORE"
shopify store auth --store "$STORE" --scopes "$SCOPES"
echo "Auth OK."
